apiVersion: v1
kind: PersistentVolume
metadata:
  name: tensorflow-files-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: "REPLACE-ME"
    fsType: xfs
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorflow-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: tensorflow-files-pv
  fsType: xfs
  storageClassName: gp2
